name = "anyi2"
compatibility_date = "2026-05-01"
pages_build_output_dir = "client/dist"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "yjas-db"
database_id = "fa9c0510-2043-4cb2-af08-0c35ab24e614"
preview_database_id = "DB" # Use local testing

# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "yjas-assets"
preview_bucket_name = "yjas-assets-preview"
